server:
    port: 9292

spring:
    application:
        name: tacos
    datasource:
        url: jdbc:mariadb://localhost:3308/tacoclouddb
        username: root
        password: 123
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
    
